### ISSUE TITLE
CLI JavaScript Wrapper to Expose Stdout, Stderr

### ISSUE THREAD

**Issue by ynouri** [Kong/setup-deck#2]
Hi,

We are Kong Konnect users and we like to use the DecK CLI to manage Kong configuration.

Since the DecK configuration is critical to our operations, we want to make sure changes to the config are properly reviewed. To implement this, we are trying to replicate the Github Actions workflow recommend by Hashicorp for Terraform:
https://learn.hashicorp.com/tutorials/terraform/github-actions
https://github.com/hashicorp/learn-terraform-github-actions/blob/master/.github/workflows/terraform.yml

One core step of this process relies on Terraform populating automatically a step output called "stdout" accessible through `steps.{{step_id}}.outputs.stdout`. 
```
- name: Update Pull Request
  uses: actions/github-script@0.9.0
  if: github.event_name == 'pull_request'
  env:
    PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
```
Note that `stdout` is not a standard output exposed by Github Actions natively. To achieve this, the Terraform team wraps the `terraform` binary CLI into a `terraform` JavaScript CLI. The JavaScript wrapper takes care of adding `stdout` as a GH Actions output. See:
https://github.com/hashicorp/setup-terraform/blob/main/wrapper/terraform.js#L40
https://github.com/hashicorp/setup-terraform/blob/main/lib/setup-terraform.js#L46

We would love to see something similar in `setup-deck` action. It would make it much easier to replicate the TF workflow, which seems a very good fit for Deck.

Thanks!

**Comment by ynouri** [comment]
For future readers this is the workflow we are using for PR comments. It leverages a file to collect the output of `deck konnect diff`

```yaml
      - name: Setup Deck
        uses: kong/setup-deck@0bd863ccce4ec68f88fc14b35a2d5a28e13bf726 # v1
        with:
          deck-version: 1.7.0

      - name: Deck Diff
        id: diff
        run: deck konnect diff --state ./src/kong/konnect.yaml > diff.log
        env:
          DECK_KONNECT_EMAIL: ${{ secrets.KONG_KONNECT_SAAS_EMAIL }}
          DECK_KONNECT_PASSWORD: ${{ secrets.KONG_KONNECT_SAAS_PASSWORD }}

      - name: Update Pull Request
        uses: actions/github-script@v4
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync("diff.log");
            const output = `#### 🦍 Deck Konnect Diff Output 🦍
            \`\`\`
            $ deck konnect diff --state ./src/kong/konnect.yaml
            ${diff}\`\`\`
            `;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
```
